### ISSUE TITLE
Problem funtion "Decrease Step" and "increase step

### ISSUE THREAD

**Issue by zarco1794** [tahoma2d/tahoma2d#1010]
### Bug Description

"Increase step",push the cells apart leaving empty places

### Relevant logs/screenshots

![Problema tahoma step](https://user-images.githubusercontent.com/39812147/174544845-52da099c-6bf9-45ba-94dd-2087e83047ca.gif)

### Software Version

1.3

### Operating System

windows 10

**Comment by manongjohn** [comment]
@zarco1794 This is not a bug. You are in Implicit Hold mode so frames are not created.

Beginning with 1.3, you are no long required to explicitly expose frames to repeat. Expose 1 frame and the image displays until either a new exposed frame is hit or you put a `Stop Hold` frame.  You can tell because "empty" frames still have a tint of the level color in them and when you are on that cell, the image of the last frame doesn't disappear.

Implicit Holds is the default setting but you can turn it off if you want to.
