### ISSUE TITLE
frame exposure issue

### ISSUE THREAD

**Issue by prince1382002kumar** [tahoma2d/tahoma2d#1019]

**Comment by artisteacher** [comment]
@prince1382002kumar - you need to give more information so that we know what the problem is. The more specific you can get, the more likely there is to be a solution.

Just an FYI, in the latest release, implicit frame holds were added as a new default. So each image lasts until a new image is added or until a stop frame hold is added (this is an option in the Timeline's context menu). If you want to revert to the old behavior (explicit holds), you can turn off implicit holds in Preferences under Drawing. You can also convert existing scenes between explicit/implicit in the Scene menu as needed.
