### ISSUE TITLE
Crash in linux when switching from plastic tool build skeleton to other

### ISSUE THREAD

**Issue by Nokse22** [tahoma2d/tahoma2d#1036]
### Bug Description

When I switch from the plastic tool "build skeleton" to something else it crashes.
It happens in the nightly too.

### Steps to reproduce

- open plastic tool
- create mesh
- build skeleton
- change to animate or anything else and it crashes!

### Software Version

1.3

### Operating System

Pop_OS!_22.04

### Graphics Card

AMD® Renoir

### Drawing Tablet

No

**Comment by GiorgioAKrenkel** [comment]
Hello, is there a Linux build available with this fix?
Thank you!

**Comment by manongjohn** [comment]
> Hello, is there a Linux build available with this fix? Thank you!

It should be in 1.3.1

**Comment by GiorgioAKrenkel** [comment]
Just downloaded the 1.3.1, and it still crashes. Imported a png image file, create mesh, add bones, animate, try to create a preview, and it crashes. It works fine, with vector, svg.

**Comment by manongjohn** [comment]
Can you send me the scene that's crashing so i can see what the problem may be?

**Comment by GiorgioAKrenkel** [comment]
Sure!! Here it is!! I dont know how to add files here, so here is a link:

[https://mab.to/t/fF6oG9ccOpN/us2](url)

**Comment by GiorgioAKrenkel** [comment]
Hello!! Any news?! I tried it on windows, and its working just fine! I believe the problem is under linux only. Maybe, because of the way it is distributed, as an APPImage?!

Thank you!

**Comment by manongjohn** [comment]
@GiorgioAKrenkel Sorry for the delay. My job has been demanding lately as the project is close to completing the final phase and haven't been able to do a lot.  Good news is it will be winding down soon.

As for looking into the issue, I had requested the scene that was crashing on you.  The link you provided doesn't work anymore. You can zip up the project/scene and attach it to a comment here.  Might be helpful to know what distro you are on and, if you can somehow get a crash log, that could be useful also.

**Comment by GiorgioAKrenkel** [comment]
Hello!! Thank you!! I am sending the scene again. The problem is present on all the distros i have tried. Ubuntu Studio, Fedora 38, Manjaro. Also, it is 
very simple to reproduce, just import any image, create the mesh with the plastic tool, then create an animation, and try to render or even a simple preview. Sometimes it freezes, sometimes it crashes. I dont know how to create a log file sorry. Again, thank you very much for looking into this issue.

[Archive.zip](https://github.com/tahoma2d/tahoma2d/files/11519758/Archive.zip)

**Comment by manongjohn** [comment]
@GiorgioAKrenkel Are you able to send me the entire project?  If you have too many scenes in the same project, create a dummy project and export the problem scene into it, then zip up the dummy project and send it to me.

If you do not wish do to that publicly, you can always join the Discord and DM it to me. Anything sent to me privately is used solely for debugging purposes and nothing more.

I originally diagnosed and fixed this particular issue in Ubuntu. What I had found was due to an issue with the custom SuperLU that was used. Switching to the system one seemed to have fixed this issue.  I'm wondering if this is potentially something new.
