### ISSUE TITLE
Change Column Names

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#114]
**Is your feature request related to a problem? Please describe**
Tahoma is Timeline oriented over the Xsheet. Col1, Col2 & etc. make a lot of sense when the Xsheet is the priority - but not in the Timeline.

**Describe the solution you'd like**
My favorite option is to name columns/layers with the name of their first level - just like how the thumbnail images are determined. Multiple levels can end up in a column/layer but it is less likely now that additional noncontiguous frames are part of the same level. This could also make it easier to identify where specific levels are located if they look similar or have thumbnails that are too small to identify.

**Comment by turtletooth** [comment]
I agree with this, but I don't think we can default to the first level name since levels can be used in multiple columns.  Is there a word besides column that is orientation neutral that works?

**Comment by manongjohn** [comment]
Are we looking at changing Col# as a reference or just what is displayed by default?  I looked at changing Col# as a display  a while ago but it was somewhat tied to column referencing.  If it's just a display thing, that may confuse users who use expression interpolations and need to use Col# as reference.

Naming a column the same as the 1st level should be fine, and something I generally agree with.  In the current behavior, if you had a column with a level with 2 frames and dragged 1 frame to an empty column, the newly populated column automatically is named the same as the prior one.  This would generally be helpful so you know they are part of the same level.

**Comment by melieconiek** [comment]
If the user enters a name in the column you'd need to make sure it's not overwritten. There are cases where I'm not going to want my columns sharing the names of my levels.

**Comment by manongjohn** [comment]
I believe when this was discussed previously, I forget who suggested it (might have been me), that the column name should appear in the New Level dialog box. If the column is empty, default to the name of level.  If it's not empty, default it to the current column name.

Use can than do what they want with the column name whenever they add a new level

**Comment by artisteacher** [comment]
> I don't think we can default to the first level name since levels can be used in multiple columns.

What if the layer number was automatically placed in front of the name?
<img width="347" alt="Screen Shot 2020-08-23 at 8 02 15 PM" src="https://user-images.githubusercontent.com/21159116/90992118-9c0c2080-e57b-11ea-82c4-60239567d4ef.png">
The numbers would have to update automatically if layers were reordered, like the current behavior.

> Are we looking at changing Col# as a reference or just what is displayed by default?

I was thinking what is displayed as default. Though, if we choose an orientation neutral term to use instead of column, expressions should probably add the ability to use the new term (or an abbreviation of) in addition to referencing columns. At this point my vote would be to use layer. I agree it could be orientation neutral.

**Comment by ladlon** [comment]
Hi.  It was suggested that I add my thoughts from my own similar thread to this discussion:

----

This suggestion will hopefully address a few things...

Currently, columns have two names... the procedurally generated one (ex. Col16), and (if added) a user-defined name (ex. Left Leg).

The current function editor displays both, resulting in a kind of messy display... plus, you are always looking for the user-defined name anyway (since that was the whole point of giving it that custom name... so it's recognizable, rather than a generic Col name.

I would suggest, if possible, that there is just one name. Each column starts with a procedural one (Col), but you can rename it to a custom one (ex. Tree) which replaces the procedural, rather than being a secondary name.

This would have the following benefits (I'd assume):

    1) The function editor list (left side) would be much cleaner, plus it would be easier to spot the identifiable (user) names, rather than the non-descriptive Col ones. With both currently being shown, the Col name only serves to make it harder to spot the user names, espeically since they are listed first (more visible, plus nicely lined up along the left margin), whereas the (more recognizable/useful) user name is tacked on at the end (not nicely lined up).

    2) Expressions that reference columns would no longer be negatively affected by the column name being renamed as the result of the column being either moved in the column stack order, or by it being nudged/renamed as a result of a new column being introduced 'below' it. Since the user name is not affected by the moving of a column, the current expression 'break' issue would (theoretically) not be an issue anymore.

    3) Expressions themselves would be far more recognizable/logical, as they would reference recognizable names/objects, rather than generic Col names (ex. Car.x vs Col13.x)

**Comment by ladlon** [comment]
Hi.  It was suggested that I add my thoughts from my similar thread to this discussion:

This suggestion will hopefully address a few things...

Currently, columns have two names... the procedurally generated one (ex. Col16), and (if added) a user-defined name (ex. Left Leg).

The current function editor displays both, resulting in a kind of messy display... plus, you are always looking for the user-defined name anyway (since that was the whole point of giving it that custom name... so it's recognizable, rather than a generic Col name.

I would suggest, if possible, that there is just one name. Each column starts with a procedural one (Col), but you can rename it to a custom one (ex. Tree) which replaces the procedural, rather than being a secondary name.

This would have the following benefits (I'd assume):

    The function editor list (left side) would be much cleaner, plus it would be easier to spot the identifiable (user) names, rather than the non-descriptive Col ones. With both currently being shown, the Col name only serves to make it harder to spot the user names, espeically since they are listed first (more visible, plus nicely lined up along the left margin), whereas the (more recognizable/useful) user name is tacked on at the end (not nicely lined up).

    Expressions that reference columns would no longer be negatively affected by the column name being renamed as the result of the column being either moved in the column stack order, or by it being nudged/renamed as a result of a new column being introduced 'below' it. Since the user name is not affected by the moving of a column, the current expression 'break' issue would (theoretically) not be an issue anymore.

    Expressions themselves would be far more recognizable/logical, as they would reference recognizable names/objects, rather than generic Col names (ex. Car.x vs Col13.x)

**Comment by ladlon** [comment]
Hi.  It was suggested that I add my thoguhts from my own similar thread to this discussion:

--

This suggestion will hopefully address a few things...

Currently, columns have two names... the procedurally generated one (ex. Col16), and (if added) a user-defined name (ex. Left Leg).

The current function editor displays both, resulting in a kind of messy display... plus, you are always looking for the user-defined name anyway (since that was the whole point of giving it that custom name... so it's recognizable, rather than a generic Col name.

I would suggest, if possible, that there is just one name. Each column starts with a procedural one (Col), but you can rename it to a custom one (ex. Tree) which replaces the procedural, rather than being a secondary name.

This would have the following benefits (I'd assume):

The function editor list (left side) would be much cleaner, plus it would be easier to spot the identifiable (user) names, rather than the non-descriptive Col ones. With both currently being shown, the Col name only serves to make it harder to spot the user names, espeically since they are listed first (more visible, plus nicely lined up along the left margin), whereas the (more recognizable/useful) user name is tacked on at the end (not nicely lined up).

Expressions that reference columns would no longer be negatively affected by the column name being renamed as the result of the column being either moved in the column stack order, or by it being nudged/renamed as a result of a new column being introduced 'below' it. Since the user name is not affected by the moving of a column, the current expression 'break' issue would (theoretically) not be an issue anymore.

Expressions themselves would be far more recognizable/logical, as they would reference recognizable names/objects, rather than generic Col names (ex. Car.x vs Col13.x)

**Comment by manongjohn** [comment]
> What if the layer number was automatically placed in front of the name?
>
> The numbers would have to update automatically if layers were reordered, like the current behavior.

There is a setting to show column number in the xsheet/timeline.  It is off by default.

> I would suggest, if possible, that there is just one name. Each column starts with a procedural one (Col), but you can rename it to a custom one (ex. Tree) which replaces the procedural, rather than being a secondary name.

I've not played much with expressions, but stuff to keep in mind:

As user entered names in columns are not unique, you can purposefully have multiple columns named the same.  I don't think we should force people to make unique column names. Consider that you might have the same level on multiple columns and want to name them the same so you know what it is.  Granted, most people would probably want to name them slightly differently so they know why it's on multiple levels.

If expressions are updated automatically, you would also have to be careful when renaming things. If you accidentally name a column the name of another column, you've essentially merged those together and would have a hard time undoing that.  Well I suppose "Undo" would have to have to keep track of what was physically changed and be able to undo only those changes.

Additionally you can put special characters in names.  This would require that the scripting be able to handle quoted column names because spaces, dots, and certain other characters in a name might cause problems, especially if external scripting was involved.

Display wise, if it's showing both names and it doesn't make sense to, then I agree we should only show 1. There might be some scenarios where we'd want to be able to see both.  For those cases, perhaps a small toggle button on the interface to show Col# when you need it will help.

**Comment by ladlon** [comment]
@manongjohn: Not sure if it was in reference to my suggestion, but I'm not saying users are forced to make unique names for columns...  They would START (as they are now) with procedurally assigned names, and stay as such, unless you rename them.  So, it's perfectly fine for a user to not give any columns a custom name.  And as for the issue of two columns having the same name, I agree that would be an issue, if allowed... but I would simply have Tahoma not allow it, or (even better) add an index number after it (ex. Car1, Car2) if an identicallly named column already exists.  The user can then either leave it (since it is made unique by the number at the end) or realize the 'mistake' and rename it something else.  Kind of what Windows does if you try and name a file the same name as one in the same directory.

**Comment by ladlon** [comment]
Ya, I am not surprised there are a few technical issues that have to be dealt with under the hood... but I'm not sure they would be too difficult, or could not simply be disallowed in some helpful way.  The bottom line is, the current system does result in the displayed expression being incorrect if the target is moved... and that strikes me as far worse than (for example) not allowing special characters in columns.  Remember, too, that special characters are only an issue if the column is to be referenced in an expression, which is not likely a very common occurance.  If it DOES happen, perhaps simply trigger an alert saying that the column needs to be renamed, if you DO try and use it in an expression.

**Comment by ladlon** [comment]
As far as the dual name display in the left side list...  Certainly a toggle would be welcome.  I'm not sure why anyone would want to use the Col names (as opposed to custom names)... but then again, I can't speak for others.  I just personally don't see why they would be used over custom names.  One could argue that it's good form to name all columns, but it's naive to think everyone is going to do that... so, I certainly wouldn't want to force it.  But, the dynmaic nature of the (program-assigned) column names is certainly an issue when trying to reference them (as if they were statically named).

Even IF you would insist on displaying both names in the list (for some reason), I'd think having the custom names first would be better... or, again, a user preference between which goes first.  That's if you need to have both.  Otherwise, a toggle between one or the other in a single-name display scenario.

For me, I rename columns to they are recognizable...  A Left Leg is a left leg.... whereas Col16 is...  what?

So, that said, when I browse through (what can be a very long) column list in the function editor, I'm scanning for those custom names... I'm looking for Left Leg... not Col16.... so, having it AFTER the Col name visually makes it a bit harder to scan through the list (compared to it being alone, or at least left justified as the first item in the text block).  The Col name, for me, is just visual noise to sort through to find 'my leg'.

My 2 cents, at least... :)

**Comment by artisteacher** [comment]
>  I'm not sure why anyone would want to use the Col names (as opposed to custom names)

I feel the same way, which is why I'd like the column name to use the name of the first level (or newest level?) by default. Then you only have to name things once, unless you need different column/level names for some reason. So much easier for quick identification.

**Comment by ladlon** [comment]
Who knows... Maybe the whole Col name thing is some old-school traditional anim thing, with some purpose that escapes me.

Your idea is good, too...  Although, my philosphy has always been, make everything as optional/customizable as possible.  That way, everyone can have it their way.

**Comment by manongjohn** [comment]
> I'm not saying users are forced to make unique names for columns...

I didn't mean to imply that is what you were saying. Renaming is optional and should always remain that way.  However, when naming a column, *I* am saying we shouldn't be forced to make unique names.

> Ya, I am not surprised there are a few technical issues that have to be dealt with under the hood... but I'm not sure they would be too difficult, or could not simply be disallowed in some helpful way

Lol. If I had a $1 for every time someone thinks it isn't too difficult but turns out it is...I wouldn't be rich but can buy something really nice. :)  I've done this to myself too, thinking something should be easy, and turns out it wasn't or a simple change had bigger implications that wasn't foreseen.

Whether this is something easy or hard or something in-between remains to be seen. Just wanted to put out things for consideration, so whomever wants to handle this particular part of the request keeps this stuff in mind.

FYI, I also rename columns so they make sense to me and expect to see that in other panels.  I also find it annoying if it only shows Col# when I expect to see my custom name.  I don't mind if it shows both, but only if there is a need for me to see both.

**Comment by ladlon** [comment]
Ah, I see.  My bad.  Well, I guess my 'Add a number automatically if a duplicate exists' thing should still be valid (as it does in Windows).  That can always be renamed, too.

Ha!  Ya, that goes for animation and many other things...  The simple stuff is often the one that gives you grief.  Ya, I'm always presenting my ideas with full admission that I'm no coding expert, and EVERYTHING involves at least some level of work.  The best I can do,t though, is suggest things that don't seem like they would be unreasonable and/or ridiculously difficult.  I'm working from an almost purely theoretical standpoint.  Same with the AMOUNT I suggest... I don't necessarily expect all suggestions to be utilized... but I figure I'll throw every seemingly valid one I can think of, as I figure the best will be chosen (...and, who knows, maybe they all WILL be utilized... Never know....).

**Comment by artisteacher** [comment]
I just want to put out there that this would be great for 1.3

**Comment by artisteacher** [comment]
It's too bad that this is so complicated! As a non-coder, I see this as potentially taking 2 stages. To me, the first stage is more important.

1. Append the level name to the display of the layer name. In terms of which level (if there are multiple), the name logic should be similar to the thumbnail logic. Then display would be "Col#: Level Name". Ie. Col1: Sky, Col2: Clouds...

As part of this, there would probably be a checkbox that could enable/disable "Append level name to layer name" in the new level dialog and in preferences, for anyone that prefers the simplicity of the original names. I'd have it enabled by default.

If it's just the display of the name that's changing, expressions shouldn't be impacted? When editing an expression, the status bar could have a message to remind users that expressions just use Col#, not the appended level name.

2. At some point, if we wanted to really embrace the timeline terminology, layer name display could change to "Lay#: Level Name". In the case, Lay# would need to be added to expressions. Col# would still be supported for backwards compatibility.

**Comment by manongjohn** [comment]
I have this on my todo list for 1.3 and started some work on this but got sidetracked by other things. 🙂

While starting this I discovered I wanted to add some underlying changes for how History could display multi-action entries because a new level creation + column rename showed the rename first with non-descript additional action (the level create).

At any rate, I've determined operations where I feel the column name should just automatically take on the name of the 1st level created in it and it's partly a matter of finding where all those occur and adding logic for the column rename...which also needs to work with Undo operations.

My initial intended change would be to just change an Empty column name to have the name of 1st Level added to it. Not sure i want to muddy dialog boxes with alternate column name edit boxes as you can do that after it's created at any time directly on the timeline, but I suppose that would be a point of discussion.

**Comment by DarrenTAnims** [comment]
_"My initial intended change would be to just change an Empty column name to have the name of 1st Level added to it"_

I think this is exactly all that 99% of users would need. Personally, it's all I need.
As an aside, if this was in place, I'd be more inclined to name my levels. As I get fed up of typing the name once for the level, then again for the column, so I tend to only change the column name as that's the main name shown in the schematics.

**Comment by artisteacher** [comment]
#939!
