### ISSUE TITLE
onion skin effect only visible when starts draw new drawing

### ISSUE THREAD

**Issue by cessna11** [tahoma2d/tahoma2d#1295]
Just a question: When I draw using onion skin (as usual), I need to draw first to see the previous drawing changing his color in onion skin effect. I mean the  onion skin color appears only when I put my pen on the tablet, not automatically on the next frame. 
Is it normal ? If yes, it's not really useful 'cause if the color doesn't change automatically when you go to the next frame (the new one) it's not clear that you are above the your previous drawing.

**Comment by artisteacher** [comment]
Since the frames have implicit holds by default (they continue displaying until there's a new drawing or until there's a stop hold), this is the expected behavior. So when you move to a new frame, try using the "Create Blank Drawing" command (opt+D | alt+D).  With your workflow, this should make onionskin display as expected, without needing to draw anything.  Depending on the tablet you are using, you might even be able to set this shortcut to a button for quicker access. Or you could add  the command in the quick toolbar.

Alternatively, create your levels with the number of frames you want to use at the start by setting a "To" value in the "New Level" dialog when first creating the level. This way, you don't need to create a new drawing each time. You can also use the "Create Blank Drawing" command (opt+D | alt+D) on a selection of frames to make a bunch of new drawings at once.

**Comment by cessna11** [comment]
Thanks for your answer. I understood, but may be it should be add in a new version? because it's more logical and present in all professional animation software like Harmony, Animation Paper or TVPaint etc... very close to the real light-table and paper in animator's job.

**Comment by manongjohn** [comment]
In the 1.4 beta (soon to be official) you can toggle Onion Skin for `Drawings` only or `All Frames`.  Before this change, it depended on the numbering system you were using.

The thing about `All Frames` and being on an Implicit Cells is if you onion-skin an Implicit Cells before/after it, it won't show anything because there is no change in the frame to show anything.  If you animate the column/level and there is a change in position between the Implicit Cell before and after, then you will see the onion skins.

**Comment by ABelliqueux** [comment]
@cessna11  : Could you make your issue's title a bit more specific ? It's a bit vague as is.

**Comment by cessna11** [comment]
@ABelliqueux: Done. Hope title is more precise like that.

**Comment by manongjohn** [comment]
> But, in reality, if we move away from the last drawing, we should no longer see it

I think i am/was confused by what you are looking for. So when you move off the last drawing and into the next frame, you dont want to see the last drawn frame regardless of you move down 1 or 10 frames?

You can turn off Implicit Holds so when you move to an empty frame, you dont see anything. If you then turn on onion skin and use relative onion skin framing,  then the previous drawing will show in onion skin colors immediately.

**Comment by cessna11** [comment]
well, when we move on to the next drawing, if we do not start drawing a new drawing, we continue to see the previous drawing as if we had stayed with it. For example, if I am on drawing 10, and I go to the next square without starting a new drawing, I continue to see drawing 10 as if I was still on it, even though I have moved. Hope it's a little bit more clear. Sorry if I'm not. Difficult to explain but it's a usual comportment of the onion skin tool with others animation softwares.

**Comment by manongjohn** [comment]
Is this what you are looking for?

https://github.com/tahoma2d/tahoma2d/assets/19245851/42604e43-d9d6-48a9-8787-e4346bfe1a5c

**Comment by cessna11** [comment]
YESSS!...absolutely. Sorry for my inattention. Thanks! 👍

**Comment by cessna11** [comment]
I think I didn't see this function because the name is...unusual. This option is enabled or present by default in other software which is why I thought it was a default. Sorry again.
Thanks for your help.
