### ISSUE TITLE
Saving Shortcut Keys Crashes Program

### ISSUE THREAD

**Issue by Dannnbo** [tahoma2d/tahoma2d#1421]
### Bug Description

1.4.1 Official Release
If I try to save shortcut preset, the game crashes

### Steps to reproduce

Configure Shortcuts, search for "Reset Rotation", press shortcut "Control + M", save as, "Name", save.... software crashed

I tried just saving a shortcut preset without doing

### Software Version

1.4.1

### Operating System

Windows 11

### Graphics Card

Nvidia GTX 1060 3GB

### Drawing Tablet

Huion RTS

**Comment by manongjohn** [comment]
I can't seem to reproduce this crash with your steps.  Can you reliably reproduce this? If so, please attach the crash log if one is created.

As an aside: Is there a particular reason you are doing a `Save As` afterwards? It's not really necessary since changes to shortcuts are automatically saved.  Doing a Save As will creates a Preset file of all the defined shortcuts which can be used to reload into another version of T2D (or OT for that matter) or sharing with someone else.

**Comment by Dannnbo** [comment]
It happens each time. I'm not sure why.

When I restart the program, my shortcuts aren't saved.

This only started happening when I updated to the latest version

**Comment by manongjohn** [comment]
It sounds like you are running it from a place that doesnt have the ability to write to your system. 

How did you perform the upgrade?

**Comment by Dannnbo** [comment]
I extracted the zip file into Program Files folder

**Comment by manongjohn** [comment]
Did you overwrite an existing one or move the other aside and extracted the new one?

Do you have anti virus running that might be preventing the latest T2D from writing there?

I know, on occasion, i've had windows either unzip incorrectly or my system just didnt get the right permissions when i extracted to Program Folders. Delete and try again?

One thing to check is the security on the Tahoma2D folder. Make sure you see your login is listed w/ full access.  Sometimes Windows doesnt add it.  Having admin rights isnt always enough.

**Comment by Dannnbo** [comment]
Ok thanks I will try these solutions and let you know

**Comment by Dannnbo** [comment]
I changed folder permission to full control and now it works, thank you
