### ISSUE TITLE
Vector lines aren't showing in the render preview 

### ISSUE THREAD

**Issue by Codeoloketuyi** [tahoma2d/tahoma2d#1452]
### Bug Description

When I try to preview the render of my drawing in vector layers I could not see the vector lines in the render preview

### Steps to reproduce

Create a vector layer draw a circle and color it red then activate the preview to see if the lines are there.

### Relevant logs/screenshots

![IMG_20240424_191024_476](https://github.com/tahoma2d/tahoma2d/assets/137768661/025a4258-ba6c-4da1-a08f-c0c77979fe51)
![IMG_20240424_191035_893](https://github.com/tahoma2d/tahoma2d/assets/137768661/1762760e-562c-4320-88a8-6b30f57d227e)

### Software Version

1.4.2

### Software Version Information

1.4.2

### Operating System

Window 11 

### Graphics Card

Nividia rtx 4050

**Comment by artisteacher** [comment]
Usually this happens if you drew your lines with the brush size at 0. In preferences under "Visualization" there is an option to "Show Lines with Thickness 0" - probably to help with cel shading techniques. It is on by default. Because there is no actual thickness, they won't render/preview. Fortunately, if you select the lines, you can use the pump widget to add thickness.
<img width="426" alt="Screenshot 2024-04-24 at 4 56 22 PM" src="https://github.com/tahoma2d/tahoma2d/assets/21159116/6388caf8-2ea9-4729-a665-e0c2163c189b">

**Comment by Codeoloketuyi** [comment]
Thanks so much this helps
