### ISSUE TITLE
I have problem with render of science

### ISSUE THREAD

**Issue by Defix15** [tahoma2d/tahoma2d#1614]
### Bug Description

I drawing art in this program, and when i render science my contour just disappears, idk why? Some ones can help me. I saw this problem in older versions only way can fix it,  just convert the layers that disappear to raster. 
Video with this problem - https://youtu.be/N6umJMDeBhA

### Software Version

1.4.5

### Operating System

Windows 10

### Graphics Card

GTX 1050 Ti

### Drawing Tablet

Gaomon s620

**Comment by manongjohn** [comment]
@Defix15 It's hard to know what's going on with your scene.  Did you apply any Fx? Can you share the entire scene?  It might be easier to figure out what's going on with it.

Feel free to join the Discord where I or others can help figure it, or to privately share the scene with me there.

**Comment by Defix15** [comment]
Thank you for inviting to ur discord, I'll join. This problem appears when i have colorful layer on top to do light or shadow. I want to make an animation in this program and i'm afraid that I might lose part of my job.
This my scene file. 
[scenes.zip](https://github.com/user-attachments/files/17451839/scenes.zip)

**Comment by manongjohn** [comment]
You'll need to attach more than just the scene directory. I'd need the entire project folder.  If there are other scenes in the project you don't want to send, then you'll need to export the scene to a brand new project and then zip up the new project and attach that.

**Comment by Defix15** [comment]
I think i done

[TEST.zip](https://github.com/user-attachments/files/17452055/TEST.zip)

**Comment by Defix15** [comment]
I think im done it
[TEST1.zip](https://github.com/user-attachments/files/17452078/TEST1.zip)

**Comment by manongjohn** [comment]
I don't see a problem here.

I opened your scene and it appears most if not all of your vector strokes have 0 thickness or close to 0 which is why it renders that way.  This is especially true for Level F (orange character).

You might be seeing a black line because `Preferences -> Visualization -> Show Lines with Thickness 0` is enabled, and for some reason it's showing as a more solid line instead of dashed line.  It could be showing this way due to the resolution of your display.

I would suggest going to the levels you should have black outlines on, select those strokes and pump up the line.

**Comment by Defix15** [comment]
Wow this realy help me. Thank you, u made my day! 😀😁
