### ISSUE TITLE
add group-timline

### ISSUE THREAD

**Issue by vinurd** [tahoma2d/tahoma2d#212]
Add the ability to create folders for grouping objects in the timeline. So that you can split the character into groups

**Comment by RodneyBaker** [comment]
We must assume subxsheets is not quite capable of meeting the requirement.
If you can elaborate a little more on how you see the grouping into folders would work differently than subxsheets that will help chart the course.

One possible approach might be to find a say to redefine subxsheets so that they are presented in the UI in more of a Group/Folder form.   It may be that the term 'subxsheet' as well as it's look and feel is just different enough that users don't realize how best to use them.

**Comment by artisteacher** [comment]
I definitely use sub-xsheets as an organizational method, though not everyone might consider them to be groups. Entering a sub-xsheet shows just the sub-xsheet (unless edit in place is on). Not all of the sub-xsheet "content" needs to be visible in the scene. The timing of a sub-xsheet cells is, in a way, independent of the content.

I would love to see a more intuitive way of entering/exiting sub-xsheets directly in the Timeline. I'm not sure what that would look like. Any potential changes should probably keep in mind the possibility of vector groups/strokes also being exposed in the Timeline in the future.

**Comment by artisteacher** [comment]
This is finally coming in the 1.5 release - though can be used ahead of schedule by using nightly builds. This can probably be closed.

https://github.com/tahoma2d/tahoma2d/pull/1385
