### ISSUE TITLE
Discussion: How can we make the manual easier to use?

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#337]
**Question**
A lot of newcomers seem to have a hard time navigating the manual. Are there specific ways it can be reorganized to make the information easier to find and understand?

Also, what areas are most outdated and in need of a re-write?

**Comment by ladlon** [comment]
Hi, artisteacher.  While I do struggle with the manual a bit (...kind of a visual thing), although that said, I can't see any immediate flaws with it.  Certainly nothing 'bad'.  It's actually very puzzling why it DOES seem to be a bit tricky to get through.  I've analyzed it quite a bit, trying to determine if it's something visual, like font size, line spacing, even colours used... but I'm actually kind of stumped!  The specific task procedures are nicely separated using the tinted boxes, as are tips... so that's all good.

One thing that might be helpful, although I'm not sure if it's something you have control over' is if the search would accept phrases, rather than single keywords.  For example, if you search specifically for 'brush size', it will currently search for anything with brush, and anything with size, resulting in a lot of unrelated items.  Certainly by no means a big issue, especially considering you usually only get a few results listed as part of the search... but, I figured I'd mention it.

It seems one thing that is not covered is that there is a second set of identical nodes, but with an INO suffix, which seem to be missing in the manual.  I suppose just mentioning what INO is would be all that is needed, since I assume the nodes are otherwise identical.

I suppose that the explanation for some of the inputs or settings of some nodes are maybe a little sparse...

The FX Reference section is seemingly very incomplete (and admits to that fact with a note at the start!)... although it seems like it might be redundant, as all the FX nodes are outlined in the Using Effects section, earlier in the manual (...although between the two, it would seem better to have the explanation of the various nodes as a separate section at the end of the manual, as the FX Reference seems to have been intended to be.

Perhaps each new section might have not only a picture of the window/panel being described (as it currently seems to), but have that image have each of the buttons labeled, so you can (at a glance) get an overview of what each button/display is... and, as is already the case, have detailed explanations later in the section.  I think maybe the lack of that initial 'quick glance summary/overviwe' might be slightly discouraging to those seeking a quick answer.  I would normally think that part of the (slight) frustration would be that you start at the beginning of the chapter, but then have to scroll through to find the explanation of the button you are seeking... but even THAT is not fully the case, since you have the (well organized) chapter content overview list to the left, where you can easily jump to it.  So, again... I'm really not sure what the trouble may be!

It seems to be doing everything correct... buttons/icons are mentioned both by name and image... Notes/caveats are highlighted for easy spotting...  Many subjects mentioned are hyperlinks to the appropriate page...

The 'Drag Selection Of Cells Of The Timeline' had me very confused (seemed nothing worked as it was explained)... literally until just now, when I tried it once again (to write this post).... and then I discovered what the explanations meant (vs what I THOUGHT they meant up to now).  The drag (without modifier) only seemed to move the selection box... until I realized it was red, which meant the operation couldn't be done for some reason (which also puzzled me)... until I realized that it only works when you drag to EMPTY cells.  Same with the CTRL+drag.  Once I realized that, things fell into place.  The Shift+Drag is a bit puzzling, only in that the visual effect as you are doing it is often not clear (hard to tell that the selection is cut out and the timeling closes the gap LIVE as you drag... so, initially it seems to either do nothing, or not behave consistently... but, again, I sorted that out just now... and that's not really a flaw of the wording of the manual.  Perhaps, though, that section (and similar procedure sections) might benefit from a series of images showing the results... or even a single image with arrows and notes, which outlines the cause/effect to expect.  That might make some of the explanations more clear.  It seems maybe some of the wording can me interpreted more than one way, or key points are easily missed (whether by lack of specification in the text, or by false assumption by the reader).

Sorry for the wall of text... Hopefully there's something there of some value.  As I said, the irony is that the manual APPEARS to be doing everything correct, and doesn't have most of the shortcomings I see in other manuals.

I'm continually referencing the manual as I do this first project (mostly to try and streamline my workflow, as I'm sure I'm doing some things in a less than efficient way, and that I still have a few false assumptions I need to stamp out).  If I run into anything specific, I'll certainly post here.  It IS quite puzzling, though... as the manual seems to be quite good.  Just seems, at least partially, to be a visual thing... almost like it's a dizzying wall of text.... yet, it isn't that, in reality.  Things are separated nicely.  It's like a weird psychological/visual thing!  Maybe a hint more white space between the paragraphs/sections to give some visual breathing room, and tilt the 'words vs space' ratio into something a bit more visually open?
