### ISSUE TITLE
macos installation problem. 

### ISSUE THREAD

**Issue by Sarim95khan** [tahoma2d/tahoma2d#339]
**Describe the bug**

**To Reproduce**
List steps to reproduce the behavior.
1.
2.
3.

**Expected behavior**

**Screenshots**

**Device Information:**
 - OS: [e.g. Windows]
 - Tahoma2D Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by Sarim95khan** [comment]
I cannot install tohama in my macos. I have High sierra which should be compatible.

**Comment by artisteacher** [comment]
Which version are you using? What does the crash report say?

Make sure to drag Tahoma2D out of the dmg onto the computer - to Applications or etc. When opening the first time, you need to open by right-clicking in Finder and choosing open. In the dialog that opens, choose “open anyway”. The first launch will fail. Afterwards, trying to open Tahoma normally should work.

**Comment by Sarim95khan** [comment]
It worked but it keep crashing.

**Comment by artisteacher** [comment]
If you can share the crash report, that would help.

**Comment by Sarim95khan** [comment]
I think it has something to do with selecting Raster Brushes. When I select Pencil it instantly gets crash.

Sarim Ahmed Khan

**Comment by artisteacher** [comment]
Does the level type make a difference?  Do all of the raster brushes cause a crash or just certain ones?

**Comment by artisteacher** [comment]
Never mind, level type & brush type doesn't make a difference. This seems to just be a problem with 10.13.
![Screen Shot 2020-10-13 at 1 51 29 PM](https://user-images.githubusercontent.com/21159116/95897337-5be74400-0d5b-11eb-9c4d-d21f3acb2d80.png)

@manongjohn any ideas where this comes from?

**Comment by manongjohn** [comment]
On my macOS MV, libintl.8.dylib comes from `gettext` which is a brew installed dependency for `libmypaint`.

**Comment by artisteacher** [comment]
If we exported the 10.13 build target in the tahoma-install script, do you think that would make a difference?

**Comment by manongjohn** [comment]
As far as I know, Homebrew is just downloading precompiled libraries already compiled for your OS version. Not sure that will have any effect.

I have run across examples where they brew-compiled something where that setting might have an effect. Not sure if that applies to only casks or all brew-able objects. 

A little surprised we aren't seeing more of this with other stuff.

**Comment by artisteacher** [comment]
I'm surprised too. I just looked at the build warnings & there are about 76 that mention ____________ was built for 10.15 but linked for 10.13.

**Comment by manongjohn** [comment]
This is was a backward compatibility build issue, likely because of Homebrew'd components do not appear to support prior versions or we haven't figured how to properly do that yet.  Probably need to brew-make the libraries and their dependencies we need with the appropriate flags, but that might take a while to do and no guarantee we'll get everything.

As I currently build on 10.13 locally, this will not be a problem and will close this.

It should be noted that support for Apple support of 10.13 has ended or will end very soon.  Even Homebrew is displaying a message that they are no longer supporting 10.13.

I will continue to build on 10.13 for as long as I am able to.
