### ISSUE TITLE
Note level issues

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#484]
**Describe the bug**
Editing the text of a note level is very finicky. Using the arrows changes cell focus instead of moving the cursor. Typing an apostrophe ' deletes all of the prior text. The text box is restricted to the width of the zoomed in cell, so it's hard to see what you are doing when typing longer notes. To correct an error, you have to click and drag to change the visible area of text by selecting. It's easy to overshoot.

**To Reproduce**
List steps to reproduce the behavior.
1. Create a note level
2. Type a sentence into a note cell & press enter
3. Double-click on the cell to edit the existing text
4. Try to navigate the text with the arrow keys
5. Double-click on the cell to edit the text again
6. Click at the end of the text and continue typing - make sure to add a contraction - ie. don't

**Expected behavior**
For arrow keys to move the cursor when editing note text. For the apostrophe to make an apostrophe, not delete prior text.

What would be ideal, is for a small text editor panel to open after double-clicking on a note cell to edit a note. Then it would be easy to see what is being typed, and you could use the cursor to navigate more easily. There could be arrow buttons to move forwards or backwards along the note level.

**Device Information:**
 - OS: macOS Catalina
 - Tahoma2D Version: 1.1

**Comment by manongjohn** [comment]
The apostrophe issue is because  OT shortcuts are still allowed while renaming cells.

I recall my irritation I had after fixing this issue in OT only to have my change partly reverted (OT PR 1451) because I was told the Japanese studios wanted this behavior despite the fact it was messing everyone else up.  In part, I believe this also had to handle entering edit mode when you single-click a cell.

The compromise (if you want to call it that) was a Preference setting that would not allow some OT shortcuts to be applied.  This setting does not apply to all OT commands, mostly just basic cut/paste/undo/redo commands.

Barring a note text dialog box being created (potential enhancement in the future), how do we want to handle OT commands while in Rename edit box?  Change it so no OT shortcuts are applied while renaming regardless of level type? No OT shortcuts only while editing a Note Level?

Thoughts?

**Comment by artisteacher** [comment]
Personally the only shortcuts that I can see being helpful while renaming are the default cut/paste/undo/redo/enter commands. I'd have the rest disabled, regardless of level type for consistency. Then maybe the arrow keys could navigate the text...
