### ISSUE TITLE
Saving issues when using Expressions 

### ISSUE THREAD

**Issue by artisteacher** [tahoma2d/tahoma2d#536]
**Describe the bug**
As reported in Discord, save-all won't run if using an expression in the scene. On Big Sur, saving a scene with an expression causes a crash.

**To Reproduce**
1. Add an expression to a column - ie. random(-10,10)
2. Use the Save-All command

**Screenshots**
<img width="655" alt="Screen Shot 2020-11-29 at 10 31 58 AM" src="https://user-images.githubusercontent.com/21159116/100548695-27ace180-323c-11eb-9e96-7fba2e98a3ec.png">

**Device Information:**
 - OS: macOS Big Sur
 - Tahoma2D Version: 1.1

**Comment by manongjohn** [comment]
This is due to saving an expression on a channel where Expression Unit = ° (degree symbol), like on the Rotation channel. When saving to file, it attempts to write it out the symbol in a quoted unicode string format. It does not have issues writing it out on Windows, but on macOS, it fails to write it out, preventing the save of the file.

Will post a workaround shortly...
