### ISSUE TITLE
Unticking, Enable Autocreation doesn't disable all of the auto creation options

### ISSUE THREAD

**Issue by DarrenTAnims** [tahoma2d/tahoma2d#577]
**Describe the bug**
In the Drawing section of the preferences, there's the AutoCreation group. If you untick the top item, it greys out the other items, but their features still work!

**To Reproduce**
1. Add a level, so that there's 1 drawing in frame 1.
2. Extend this for a number of frames
3. Click in frame 2.
4. Open the preferences and tick all 4 tickboxes in the auto creation section (image 1 below)
5. Close the preferences. Click into frame 2 and draw. Note that drawing #2 is created.
6. Open the preferences and untick the top tickbox, labelled, "Enable Autocreation". Note that the 3 grouped tickboxes are now greyed out, but showing a tick.
7. Close the preferences. Click into frame 3 and draw. Note that drawing #3 is created. It should not create a drawing.

**Screenshots**
Image 1: All 4 boxes ticked
![image](https://user-images.githubusercontent.com/28575907/107264918-814f3a80-6a3b-11eb-9045-1ac16628b4e2.png)

Image 2: Top tickbox unticked. Note other 3 showing a tick
![image](https://user-images.githubusercontent.com/28575907/107265066-bbb8d780-6a3b-11eb-9da8-2465fcffef53.png)

**What should happen**
If you untick the top box, the other 3 boxes should grey out, untick and their functions not be enabled. i.e. you shouldn't be able to auto-stretch frames or create drawings in hold cells.

**Comment by manongjohn** [comment]
I was working on making all the options dependent on `Enable Autocreation` based on how they are currently grouped, however, after reviewing the intended behavior of some of these options, I propose to break out the options as follows because some are still useful when Autocreation is turned OFF, but you use `Create Blank Frame` or `Duplicate Frame`

1. Enable Autocreation
   - Enable Creation in Hold Cells 
2. Enable Auto-stretch Frame
3. Numbering System
4. Enable Autorenumber

Thoughts? Concerns?

**Comment by DarrenTAnims** [comment]
This sounds good. I believe the "Enable Autocreation" option means that you can start drawing in a blank cell and it'll create a drawing. And if so, I can understand why you might add "Enable creation in hold cells" as a dependant on this, but they do seem like similar options, not necessarily with a dependency. Could they just not sit side by side, to show the 2 variants and be independently selectable? Do they need this dependency?

* Enable autocreation in blank cells
* Enable autocreation in hold cells

**Comment by manongjohn** [comment]
Does it need the dependency? No, not really. They can be decoupled.  I suppose technically because of this "bug" it currently is. lol

I was planning on adding a `Toggle Autocreation` button (along with `Toggle Auto-stretch Frame`) somewhere on the Timeline probably after the next release. Does this mean I would need 2 if they were separate? Would just adding a `Toggle Blank Cell Autocreation` button and have users go to preferences to toggle the other be acceptable?

I'm a little iffy about decoupling it at the moment with no real justification for why not to. If it makes more sense to separate them, then I will.

**Comment by artisteacher** [comment]
> I was planning on adding a Toggle Autocreation button

Yes, please!

Personally I feel like users are unlikely to want autocreation in hold cells if they don't want autocreation in blank cells.

**Comment by DarrenTAnims** [comment]
I 100% agree @artisteacher. It's unlikely that you'll want to auto-create in hold cells, but not on blank calls. But they still feel like 2 independent, but tightly related, features mushed into a grouping. Please don't misunderstand, I'm not strongly opposed to having them as they are now. I just don't know if it helps or if it's clear, especially with the naming of the "Enable autocreation" option. And if you name it clearer to, "Enable autocreation in blank cells", which is was it is, then it no longer is a grouping option for "Enable creation in hold cells". I'm just after clarity. If you believe it's clear, I'm happy to accept it, now that the original issue is fixed.

**Comment by DarrenTAnims** [comment]
> I was planning on adding a `Toggle Autocreation` button (along with `Toggle Auto-stretch Frame`) somewhere on the Timeline probably after the next release. Does this mean I would need 2 if they were separate? Would just adding a `Toggle Blank Cell Autocreation` button and have users go to preferences to toggle the other be acceptable?

Tbh, I'm more likely to want to toggle the creation in hold cells, than the creation in blank cells. That's the only option of the 2 that I ever change. But I'm possibly not your target audience :-) Could those options be added on a command bar? So then the user could decide which options they want to show?

**Comment by artisteacher** [comment]
> I'm more likely to want to toggle the creation in hold cells

Same here

**Comment by manongjohn** [comment]
I think I will leave it for now, and we can readdress it when i make those buttons available.
