### ISSUE TITLE
Transparency/fade effect working in one project but not another. Is this a bug or am I doing something wrong?

### ISSUE THREAD

**Issue by turboboy215** [tahoma2d/tahoma2d#600]
**Describe the bug**
I am new to using this animation program. When I started working on an animation project, I was able to use the transparency effect to create a "fade in" effect at the beginning, which I also intend to use at the end. Later, I saved the project as an updated version, and sometime later, I noticed that the effect wouldn't work anymore, no matter how hard I tried, but the fade effect in the original project works. I have checked all the FX settings in the schematic window and they all seem to be the same, so I am unsure whether I am doing something wrong or if this is a problem with the program itself.

**To Reproduce**
List steps to reproduce the behavior.
1. Open the file "IntroNTI1.tnz" in the attached ZIP file.
2. Select the "preview" mode and hit play. You should see a fade in effect at the beginning.
3. Now open the file "Intro NTI1b.tnz".
4. Again, select the "preview" mode and hit play. You will notice that there is no fade in effect; it just shows the opening image as if there was no transparency effect.

**Device Information:**
 - OS: Windows
 - Tahoma2D Version: Oct 29, 2020
 - GPU: NVIDIA GeForce GTX 1070
 - GPU Driver Version: ?

**Comment by artisteacher** [comment]
@turboboy215 - I don't see any files attached. I would double-check and make sure you have keyframes for the transparency value on the frames you expect them to be on.

**Comment by turboboy215** [comment]
Sorry, I forgot to attach the ZIP file. It was actually too big, so here is a link:
https://drive.google.com/file/d/1tLVIDGvs-GA6hOrlmS6_sffrkoqZxAPK/view?usp=sharing

**Comment by DarrenTAnims** [comment]
We don't have access to that file. You need to change the permissions to allow us to download it.

**Comment by turboboy215** [comment]
The link should work now.

**Comment by DarrenTAnims** [comment]
Thanks. That downloaded now. I can see why it was so large though. Its your whole sandbox. It'll make your life easier if you create new projects for your scenes. But here's a video that'll help when sharing projects, to be able to share only the scene that you want to share, instead of your whole sandbox: https://youtu.be/j6GbCD5lySE

And I can see the problem. If you look at your fx schematic in the working version, "IntroNTI1.tnz" you'll see that your transparency node has Col3 plugged into it, but on the broken scene you've got Col1 plugged into it. Plug in col3 instead and you'll see your fade in.

**Comment by turboboy215** [comment]
Thank you! I don't know how I missed that...
