### ISSUE TITLE
Crashes when trying to open projects created in OpenToonz. (v1.1 on Linux)

### ISSUE THREAD

**Issue by quirinux-so** [tahoma2d/tahoma2d#603]
**Bug**
Tahoma 1.1 for GNU / Linux crashes when trying to open projects created in OpenToonz.

**To Reproduce**
List steps to reproduce the behavior.

1. Create a file in opentoonz with a raster level and another vector. Close Opentoonz.
2. Open Tahoma and find the project path (no problem).
3. Select the scene (file.tnz). This is where the program crashes.

**Important**
Afterwards, it is impossible to reopen the scene in OpenToonz (the file that we could not open in Tahoma seems to be corrupted after the attempt). Error message: "The scene cannot be loaded because it does not belong to any project."

**Device Information:**
 - OS: Debian 10
 - Tahoma2D Version: 1.1 Beta
 - GPU:  Intel Graphics (onboard)
 - CPU: i5
 - RAM: 8 GB

**Comment by manongjohn** [comment]
Are you able to attach the .tnz file that is crashing?

**Comment by quirinux-so** [comment]
> Are you able to attach the .tnz file that is crashing?

Hello, yes, I share it. Thanks a lot.

[http://my.opendesktop.org/s/53k4ZK9pTMS8NFc](http://my.opendesktop.org/s/53k4ZK9pTMS8NFc)

**Comment by manongjohn** [comment]
I am able to open the scene file in Windows and in Ubuntu.  I'm wondering, since you have a Vector level, if there might be an issue with the vector level causing the crash.  Have you tried loading the Vector level into a brand new scene and see if it loads successfully?

If it's not an issue with the vector level, It might help if you sent me the entire Project folder.

**Comment by quirinux-so** [comment]
Thanks for the suggestion. I did the test and was able to load the vector level without problem in Tahoma. I enclose the complete project.

[http://my.opendesktop.org/s/jSyisSS2cZwJmK5](http://my.opendesktop.org/s/jSyisSS2cZwJmK5)

**Comment by manongjohn** [comment]
Ok.  It loaded fine for me on Ubuntu 16.04, but crashed on me in Ubuntu18.04.  I'll see if I can figure out why.

**Comment by manongjohn** [comment]
Sooo.....apparently I was running a more updated Tahoma (has stuff for next release) where it loaded fine, but when I tried with the orignal 1.1 release it crashes.

So...good news, whatever the issue was is fixed. Bad news it won't be fixed until the next release as I don't have any nightlies.

For now, you can use OTX to continue working on it.

**Comment by quirinux-so** [comment]
Thank you very much, I will be looking forward to the version in .appimage (I could not install it in Buster otherwise). Greetings.
