### ISSUE TITLE
Can't set spacebar as a keyboard shortcut (v1.1)

### ISSUE THREAD

**Issue by quirinux-so** [tahoma2d/tahoma2d#604]
**Description**
I can't define the space bar as a keyboard shortcut. I used to assign it to Play in original OpenToonz.

**To Reproduce**
List steps to reproduce the behavior.
1. File 
2. Configure shortcuts...
3. "Play" (search)
4.  Remove
5. Press spacebar

**Versión**
Tahoma 1.1

**Comment by manongjohn** [comment]
This is not a bug. It was an intentional change made for 1.1 because space was used specifically for certain viewer operations and using space as a shortcut broke it.

I have already decided to reverse this restriction with PR #588, which will be in the upcoming release. Feel free to test out the artifact.

**Comment by quirinux-so** [comment]
> This is not a bug. It was an intentional change made for 1.1 because space was used specifically for certain viewer operations and using space as a shortcut broke it.
> 
> I have already decided to reverse this restriction with PR #588, which will be in the upcoming release. Feel free to test out the artifact.

Oh thank you very much. Those of us who come from audio editors are very used to hitting "play" with the space bar. I am eager to try the next version, especially for the compatibility with OpenToonz projects. Please also release it in .appimage format. Greetings.
