### ISSUE TITLE
Working without creating a project first, Tahoma can lead you to believe that you've saved your work, when you haven't

### ISSUE THREAD

**Issue by DarrenTAnims** [tahoma2d/tahoma2d#605]
I know you should create a project, then scene before you start drawing, but new users don't know this and Tahoma didn't warn me about it not saving my drawings.

1. Run Tahoma2D
2. Create levels and start drawing
3. Hit **Save All**. Give it a name

You can now close Tahoma for the session, believing that your work is safe.
Note that on disk, Tahoma hasn't created a project or the related folders. It just saved the scene file, but **NONE** of your drawings!
When you reload, you see the red drawing numbers in your timeline.

**Comment by manongjohn** [comment]
Odd. You always start off in a project, even when you start off blank. Did you change the location of where it was saving to?

**Comment by artisteacher** [comment]
Everything should save in the sandbox if you haven't made any projects.

**Comment by manongjohn** [comment]
I am able to duplicate this issue if I save a scene outside the current project and not in another project. I can get similar results in OpenToonz as well so it isnt unique to Tahoma.

Using the Tahoma 1.1 release, i can definitely cause this. Using the upcoming release, I can't. It might be because of the changes I made to not save assets until you actually save.

That being said, it is still an issue because the scene file is being created outside the project folder but everything else is still being saved in the current project folder.

Need to fix it so that if it doesn't detect the save location is in a project folder, it will prompt the user to create a new project at that location.

**Comment by DarrenTAnims** [comment]
Thanks for the replies. So I've played with this a little more. I guess @manongjohn, when you talk of saving the scene outside the current project, the current project is the sandbox. So in that case, yes, I'm saving it outside the current project. But as I'd not set a project, I hoped it would create a project folder structure for me when I first saved. But if it's using the Sandbox by default, I guess I am choosing to save outside the project. Is this clear for users?

I checked if my drawings had saved in the Sandbox @artisteacher, but they hadn't. I hadn't mentioned it, but I'd created vector levels. If I so the same, but create raster or toonz raster levels, then they're saved in the sandbox on creation, so the issue is that the vector isn't created on saving. So when I hit Save All, I choose where to save the scene and it can't find a folder to save the vector level in. I imagine this will be the same for the other 2 level types in the new system but I've not got a recent version to test this in.

And yes, I assumed this would be an issue in OpenToonz too.

FYI, this isn't really an issue for me 99.99% of the time. I was quickly throwing an image together and decided to save it afterwards. Ordinarily I'd create a new project/scene first. But I reported this because it's something that new users could do and could come across.

**Comment by artisteacher** [comment]
> But if it's using the Sandbox by default, I guess I am choosing to save outside the project. Is this clear for users?

This is part of why I'm not a fan of the sandbox. After a new install, if I don't create a project/scene on start & then choose to save, I'd rather be prompted to create a project...

**Comment by manongjohn** [comment]
> But as I'd not set a project

You are always in a project whether you realize it or not.  If you never set it, then it's the default sandbox.  As much as I dislike the sandbox, it's a starting point.

The problem is when you save for the 1st time or use save as, if you choose a location outside the current project folders, it will allow you to save just the scene file, but the rest of it would/should be saved in the current project's folder, which is a problem for many different reasons.

OT, in this scenario, typically warns you if you are saving outside the current project folder, using the sandbox as the default if the location is not part of a project.  For some reason this warning does not come up in Tahoma.  Additionally, it still allows the user to separate the scene file from the rest of the project.  While Tahoma may be able to put things together, it would be confusing to users since not everything is in 1 spot anymore.

I will have to make a change that when you try to save a scene in a different location, it will check to see if the target folder is part of a Project.  If so, it will use that project.  If it isn't the same project, it needs to ask you to switch or force you back to the current project folder.  If the target folder is not associated with any project, it will need to ask you to either create one or force you back to the current project folder.

**Comment by DarrenTAnims** [comment]
Yeah, If the vector levels had saved in the sandbox, it wouldn't be so bad. I could assemble my project back together again, but they  weren't saved at all.
But it's the default project that's a little surprising. As you say, if Tahoma recognised that you'd saved the scene outside of the "current project" and create the project hierarchy and saved the drawings in there, that'd be awesome. And I suspect that it would stop some of the Red Drawing reports that we read about so often.
And with OpenToonz having fixed project locations, I'm not sure what could be done there.
As I've said (I think), I'm not trying to give anyone more work to do. I'm just trying to stop these red drawing reports and make it less easy to lose data.

**Comment by DarrenTAnims** [comment]
Another thing that doesn't help with the notion of the current project being the sandbox is that it doesn't say Sandbox in the title bar. If you create a project & scene using the startup popup, it lists those 2 in the title bar. If the title bar said something like this, it'd be a little clearer: "**Untitled Scene [Project: Sandbox]**"

**Comment by artisteacher** [comment]
I believe this is fixed and can be closed.
