### ISSUE TITLE
Ability to Vertically/Horizontally flip selections/frames 

### ISSUE THREAD

**Issue by PinkalineProwess** [tahoma2d/tahoma2d#627]
It would make things 20x easier and streamlined if you could flip frames and/or selections vertically/horizontally, rather than editing H/V values and having to put it on a separate column if you want to do different H/V rotations for different frames.

The regular way is so tedious and you have to make a separate column (as it rotates via columns rather than frames), which makes it clunky. 

(Sorry if this is confusing to read, I admit I'm not the best at wording things)

**Comment by artisteacher** [comment]
With the Selection Tool, it's very easy to flip a selection - just change the H or V value to a negative number. It's quite fast. The change only applies to the active selection. 

Of course, if the layer has a single drawing exposed for multiple frames, then sure, the entire display of those frames will change, since it is a single drawing. Making changes to a selection doesn't make a new image. In that case, just duplicate the drawing (right-click on a cell and choose "duplicate drawing") before changing the H/V value for the selection. No need to make separate layers unless you want to.

**Comment by PinkalineProwess** [comment]
Oh my goodness I'm silly!! I didn't realize it was already possible, my apologies! I must've missed it because I was flipping the entire frame rather than selecting it all and flipping it that way. 

Thank you for bringing it to my attention, kudos! :)
