### ISSUE TITLE
 Geometry tool (Arc, MultiArc) graphic tablet - Linux

### ISSUE THREAD

**Issue by andeon** [tahoma2d/tahoma2d#629]
I originally opened this bug issue in opentoonz, but as it affects Tahoma2d as well, I believe it is necessary to put it here as each project follows a direction. 

In short, the arc and multiarc tool doesn't work correctly when drawing and  adjusting the angle of the lines with graphics tablet.

Here the link to issue https://github.com/opentoonz/opentoonz/issues/3826 if necessary I can copy paste here too.

**Comment by manongjohn** [comment]
Usually not necessary to repost OT issues in Tahoma. Most times issues in OT also inherently affect Tahoma the same way...for now at least.  I do keep an eye on OT bugs and fixes and see how they might relate/apply to Tahoma.

At any rate, I do have a problem with Arc/MultiArc in Windows using a pen. When I tap with my pen, it somehow does both endpoints in roughly the same spot and then moves directly to adjusting the arc.  No problem with mouse. Not sure if anyone is seeing this in macOS.  

Issue might be related.  I will look at fixing from a Windows point of view and see how that affects Linux version.

**Comment by artisteacher** [comment]
I'll check on the macOS end.

**Comment by manongjohn** [comment]
Thanks @artisteacher.  Let me know.

Playing around with it, I found that with Windows Ink Enabled in Tahoma, it works fine.  When I disable Windows Ink, it doesn't.

Looking at the pen/mouse events, I see the problem when Windows Ink is disabled.  Somehow it's processing a MousePress event between the TabletRelease and the MouseRelease events.  This extra MousePress is causing the second click to be registered right away and fixes the second endpoint which is why it moves directly to the arc logic for me.

This issue affects my other tools as well but may not really be noticeable. With Vector brush, it creates an extra tiny stroke at the beginning.

If any other Windows users have similar issues when Windows Ink is disabled, please let me know.

**Comment by andeon** [comment]
@manongjohn I always used OpenToonz, Tahoma2d without "Windows ink" enabled, I don't remenber this problem. It is necessary to consider the driver issue. Anyway, I tested the artifact for Windows with "Windows Ink Support" enabled and disabled and I don't see any problems here. 

I say again, thanks for fixing it on Linux :)
