### ISSUE TITLE
won't let me pull up projects

### ISSUE THREAD

**Issue by Holly1001** [tahoma2d/tahoma2d#732]
**Describe the bug**
when I try to click on a project, it freezes and refuses to load. 

**To Reproduce**
1. Open Tahoma
2. Cick on a project

**Device Information:**
OS: Windows
Tahoma2D Version: version 1.0.1
GPU: [e.g. NVIDIA RTX 2080]
GPU Driver Version: [e.g. 440.00]

**Comment by DarrenTAnims** [comment]
Your Tahoma is very out of date, so if you can, I'd suggest upgrading to the latest version. That might help. You might be suffering from a problem that's been fixed many months ago.

**Comment by artisteacher** [comment]
I agree that you should update to the most recent version of Tahoma. If you do so and still have issues, we'll need more information in order to help. 
- What version of Windows are you running? 
- Is it actually the scene that won't load?
- Do you have the same problem with every scene/project, or just specific ones?

**Comment by Holly1001** [comment]
completely forgot to close this but updating fixed it.
