### ISSUE TITLE
dark theme problem in windows 11. and it is unable to use in windows 11 pls update the software according to windows 11 

### ISSUE THREAD

**Issue by mrsingara** [tahoma2d/tahoma2d#749]
**Describe the bug**

**To Reproduce**
List steps to reproduce the behavior.
1.
2.
3.

**Screenshots, short videos or   #@logs**
If applicable, add screenshots or links to short videos to help explain your problem or provide logs or dmp files if it's a crash.

**Device Information:**
 - OS: [e.g. Windows]
 - Tahoma2D Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by manongjohn** [comment]
Please provide screenshot.

For future issue post, please put the description in the body and just a short description in the title. 

Thanks.

**Comment by mrsingara** [comment]
OK I AM PROVIDING SCREENSHOT  . PLS NOW HELP ME SOLVE THIS PROBLEM ITS HAPPENING IN WINDOWS 11 USERS 

![tahoma_ss](https://user-images.githubusercontent.com/88938511/129469140-ce27b2e8-574e-46a0-9d7c-2e308bb1add1.png)

**Comment by mrsingara** [comment]
THIS IS THE PROBLEM I AM NOT ABLE TO CHANGE THE THEME

**Comment by artisteacher** [comment]
Is the tahomastuff folder in the same directory as the tahoma2d executable?

**Comment by mrsingara** [comment]
yes

**Comment by manongjohn** [comment]
Did you fully extract the Tahoma2D folder out of the .zip file and move the entire folder to somewhere else on your machine like Desktop or something?

The screenshot basically tells me it is having problems reading/finding the configuration folder. 

Are you able to even use it and save stuff?

**Comment by mrsingara** [comment]
I DONT KNOW BUT I THONK I HAVE EXTRACTED THE FULL FROM ZIP FILE

**Comment by mrsingara** [comment]
NOW I AM REINSTALLING IT
THEN SEE WHAT HAPPENS THEN
IS THIS APPLICATION APPLICABLE FOR WINDOWS 11

**Comment by manongjohn** [comment]
Please don't respond in all caps..it is equivalent to shouting.  Thanks.

As for running in Windows 11, I don't know.  I don't know why it wouldn't work. I don't have a Win11 machine to see if I can duplicate this issue and don't know of any who has Win11 at the moment.

I have seen this issue once before even on Win10 and it appeared to have an issue accessing something, though I can't remember the actual cause.

- You still have not answered if you are able to use it at all, like draw and save something even though the theme isn't loading right. Can you even use it or does it crash?
- Can you provide a screenshot of your file browser where you are running Tahoma2D.exe from so we can see where you are running from and make sure everything is there.
- Have you tried running it as Administrator in case it is having trouble accessing something due to permissions?
- Can you check the Security information on the `Tahoma2D\tahomastuff` folder and make sure you see your login is listed with full permission?

**Comment by mrsingara** [comment]
OK AFTER RE INSTALLING THE SOFTWARE WORKS WEELL DONE

**Comment by manongjohn** [comment]
As this has been resolved, somehow, closing.
