### ISSUE TITLE
Cursor pointing on wrong place in timeline tab- Mac

### ISSUE THREAD

**Issue by kucharskikucharski** [tahoma2d/tahoma2d#772]
Hello, my problem for today is:

the keyframe dragging point of cursor is in different place.
Not sure I'm describing this bug correctly so I give screen recording (sorry for poor quality).

I have problem with NVIDIA Drivers, maybe thats the case, but in other hand all tools like control point editor works fine.
I think it's something with timeline

https://user-images.githubusercontent.com/45039631/131728540-55d29033-50c0-47f9-bb1a-06fa61c81150.mp4

Tahoma2D 1.2
Build: May 12 2021

Mac (27-inch, Late 2012)
Procesor 3,4 GHZ Quad Core Inter Core i7. 32 GB ram 1600 MHZ DDR 3.
Grafika: NVIDIA GeForce GTX 680 MX 2GB
System: macOS Catalina Version 10.15.7

Cheers!

**Comment by artisteacher** [comment]
I agree that something seems a bit off with the cursor at times.

My guess is that the cursor's outline is not being recognized as part of the cursor. So when just the edge/tip of the cursor overlaps something - ie. a keyframe, a drag handle, a style swatch or etc., we think we are aiming at the correct place, but whatever action we are trying doesn't happen as expected. I think this is particularly noticeable in the Timeline due to the small target areas, but it can happen elsewhere too.

**Comment by manongjohn** [comment]
I did notice when I was working on applying OT patches that  trying to click on keyframe stuff was off, and admittingly a bit difficult at times.  When I adjusted the keyframes as part of one of the OT patches, i think it improved it a little bit.  I suggest downloading the latest nightly and see if it helped any.  There might still be a need to adjust the area of activation.
