### ISSUE TITLE
The option to see the canvas color through the camera area

### ISSUE THREAD

**Issue by F-Burning** [tahoma2d/tahoma2d#858]
I think a good option would be the possibility to see the canvas of the level through the camera , beyond the actual white rectangle.

For example, the camera here is 1920x1080, and the level size is 2200x1500:

![01](https://user-images.githubusercontent.com/74098734/148465926-0218ef2f-582a-4b12-8451-77ff0822972d.png)

You can draw and see what you are doing, but I think a better option is to be able to see your entire canvas like here:

![02](https://user-images.githubusercontent.com/74098734/148465927-cb4cc888-f796-4d13-98c2-7c2b2f789037.png)

I know is possible change the camera size, but I would like to keep the resolution and be able to draw seeing the white color, in this case, at least as an optional choice in preferences! Simply, when you change between levels with different sizes, you will be able to see them reflected on the screen.

What do you think?

**Comment by artisteacher** [comment]
Levels actually have a transparent background/canvas, which is why we currently don't see the white bg color outside of the camera. Making things more complicated, vector levels don't have a size - you can keep drawing indefinitely. So if the white area was expanded to the level size, the viewer would be entirely white for vector levels - might be a little hard on the eyes. Also, you'd lose some of the sense that the levels are transparent.  Not that the transparent bg is necessarily clear to new users if their level size is the same as the camera...

That said, it can be hard to see what you are drawing in some cases - especially when the level strip is active #496. This certainly should be addressed.

In the meantime, if you'd like to change the background color of the viewer, so that you can see dark lines or etc. more easily, there's already a preference. Just uncheck "Use current theme's viewer background colors" and then adjust the sliders as needed.
<img width="661" alt="Screen Shot 2022-01-07 at 10 04 21 AM" src="https://user-images.githubusercontent.com/21159116/148563035-0264c365-560a-4338-985f-9aded1772e26.png">


At some point, what I'd really like to see is a value slider for the viewer background. Something accessed directly in the viewer controls in order make adjustments on the fly based on the needs of the particular scene or level. The setting would save with the scene.

**Comment by F-Burning** [comment]
That's true, but I think this option is not necessary in Vector level because you can configurate the canvas color as you said, but in raster level, so this would be only in this kind of "layer"

I think a good alternative could be the possibility to add margins to the camera, in this way you can see the camera frame in the original resolution, plus the margins like here:

![Ilustración](https://user-images.githubusercontent.com/74098734/148597841-8393dba7-e7e5-45d2-af1b-783f90374764.jpg)

This only rendering the camera resolution, and the margins only exist to make easy the drawing process and make big scenes out the camera. 

Here you could add the margins check to make levels like the camera + margins size

![po](https://user-images.githubusercontent.com/74098734/148598224-f4ae84b5-94fe-493b-bd5d-577dfe578b57.jpg)
