### ISSUE TITLE
Convert vector to smart raster bug

### ISSUE THREAD

**Issue by F-Burning** [tahoma2d/tahoma2d#915]
There is a bug when you try to convert colors from vector level to smart raster.

**To reproduce:**

1. Create a vector level.
2. Draw anything.
3. Choose a different color than black (red for example)
4. Select the frame.
5. Go to Level -> Convert -> Vector to Smart Raster.

**Expected result:**

The line converted will be red.

**Obtained result:**

The line converted is black.

**Comment by artisteacher** [comment]
I'm not seeing this on macOS. My colors display as expected in the converted smart raster level.

**Comment by manongjohn** [comment]
I can reproduce this.  What's happening is when the smart raster level is created, it is created with the default smart raster palette.  Existing style indexes in the default smart raster palette are unchanged and only new styles found in the vector level are added to the smart raster level. Need to fix it to update the existing styles to maintain style-index.

FYI, This happens with OT too actually though it's probably worse in T2D because we can set up our own default palettes.

**Comment by F-Burning** [comment]
I see @manongjohn, that makes sense, happy you find the problem.

Thank you!
