### ISSUE TITLE
Bring back'Sec Frame' in Xsheet

### ISSUE THREAD

**Issue by F-Burning** [tahoma2d/tahoma2d#932]
I don't like so much lose this option, because it's useful

![0p](https://user-images.githubusercontent.com/74098734/158828634-be619fdd-eb85-4aa7-bdff-3e01bb3e74a9.jpg)
 
I know that you can see the time in the visor, but for me is much more confortable as in the image above

Could be possible get it back?

**Comment by artisteacher** [comment]
What parts of the "Sec frame" display do you prefer? Personally I'm not ever going to use the "Sec Frame" options because my brain just doesn't work that way. Despite that, I could still see a benefit to a time indication in the Timeline itself.

I'm just wondering if instead of reverting the code, developing a sort of hybrid solution might be a good option. What if a timing indication was added into the Timeline in some way in addition to the frame numbers? Perhaps a preference (or context menu commands) to add seconds (or 3sec or 6sec) above the frame numbers - the space is still there. Maybe also an option to just have a line indicator (without a number) or even no indicator for those who want less clutter.

**Comment by F-Burning** [comment]
I think "Frame" and "Sec + Frame" are fine.

I still prefer the Opentoonz solution, because it's optional and it's useful for everyone, but If the code is the problem, the hybrid solution with the seconds + frames in the timeline/xsheet could be good too 👍

**Comment by manongjohn** [comment]
Restoring the code isn't the issue here.  Trying to provide a more user friendly UI is.

I think a bulk of T2D's user base are independent/novice artists and the OT UI is very confusing and can be intimidating, not Blender intimidating, but being presented with every available option can be visually overwhelming and quite confusing when first learning the program.

For this reason a number of non-essential things have been hidden to simplify the UI.  This is definitely not essential.

I was contemplating a Preference - Interface setting to `Show Advanced Controls` or something to that effect, to hide/unhide some of these hidden options for those familiar with OT and want to use them.  It's sort of on my TODO list, but not that high on the list.

**Comment by artisteacher** [comment]
Tangentially related, https://github.com/opentoonz/opentoonz/pull/4379
